### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by neshanjo** [tswistak/react-inversify-inject-decorators-example#1]
Hi Thomasz, 

first of all: Thank you very much for this example! 

Why I'm writing: The current version cannot be build (e.g. npm start gives errors). I identified two problems: In tsconfig.json, you should have `"experimentalDecorators": true`, and in tslint.json, you should disable the quote and interface checks.

Unfortunately, I found no other way to contact you, so here some other questions:
Do you use inversify in a real world application? How do you set up unit tests, where you want to inject other services or mocks or dummy implementations? You can contact me via the mail address in my Github profile if you like. I'm about to setup dependency injection for a react application and have been reading a lot of different articles and opinions about this topic. We also use react-redux and also need DI into our actions. Any input to this is very welcome!

Cheers,
Johannes

**Comment by tswistak** [comment]
Hi!
Thanks for contacting me. I haven't checked that project for a while since it was just an example for a blog post. Apparently after some package update from CRA something has broken, but I've provided all needed fixes. Despite experimentalDecorators (I thought I had it, strange that it was working before) I've also fixed linter issues, because there have appeared some changes.

About the other part of your post. At my previous employer we were using Inversify in a few projects, which were commercial products, at which in three I had an opportunity to work. As for unit tests, unfortunately I won't help you in this. In Inversify projects where I was working we were providing all mock implementations by hand, without using IoC in unit tests. With constructor injection on, @inject decorator is doing nothing when you create class by "new" keyword, so providing mock implementations was pretty simple in that case. Unfortunately, for quite some time I wasn't using Inversify so I'm not really up-to-date on it, but I can help you with what I remember.

Best regards,
Tomasz

**Comment by neshanjo** [comment]
Hi Tomasz,
thank you very much for your quick and detailed reply. After all, I decided against using inversify in our project, because it relies on experimental TS features, adds much (hidden) complexity to the project and, finally, I did not get lazyInject (getDecorators) to work there. So I implemented a service factory (including lazy initialization) myself, which turned out to be less effort that I thought.
Kind regards,
Johannes
P.S.: You can close this "issue" if you like...
